# Generated by Django 2.2.4 on 2022-06-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_auto_20220616_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='old dojo', max_length=255),
        ),
        migrations.AlterField(
            model_name='ninja',
            name='dojo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='dojo_ninjas_app.Dojo'),
        ),
    ]
